### ISSUE TITLE
MultiMC fabric and Nicephore mod detection/compatibility

### ISSUE THREAD

**Issue by TheBlueGamerG** [LotuxPunk/Nicephore-Fabric#19]
I've no idea if this is an issue with MultiMC/Fabric/Mod, but i get the following error when i try to launch my client:
Error:
------------------------------------------------------
- Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
- Install fabric, any version.
Unmet dependency listing:
- Mod 'Nicephore' (nicephore) fabric-1.19.x-1.0.0 requires any version of fabric, which is missing!
at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
at org.multimc.EntryPoint.listen(EntryPoint.java:143)
at org.multimc.EntryPoint.main(EntryPoint.java:34)
------------------------------------------------------

![Screenshot 2022-10-19 000650](https://user-images.githubusercontent.com/116120105/196960928-606b8a60-2194-49bc-b7a8-fc827dba4aff.png)

**Comment by PaintNinja** [comment]
You need to install the Fabric API mod, which is a mod you install on top of Fabric.

**Comment by TheBlueGamerG** [comment]
I just came across Fabric API, decided to check if this issue has been resolved, and yep, that's what i was missing..
